"""empty message

Revision ID: 42d7a3675bdc
Revises: 3d54c45a371b
Create Date: 2020-03-16 22:58:47.521117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d7a3675bdc'
down_revision = '3d54c45a371b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###
